### ISSUE TITLE
缺少class文件，不能在其他环境配置使用

### ISSUE THREAD

**Issue by feathershine** [inkss/hotelbook-JavaWeb#7]
麻烦给个release版本可好，还想直接看看效果呢，没有可以直接部署到服务器上的shell脚本么（

**Comment by inkss** [comment]
上IDEA编译一下就出来了，滑稽。

[hb.zip](https://github.com/inkss/hotelbook-JavaWeb/files/1570315/hb.zip)

把这个解压到tomcat的webapps里，浏览器访问`http://localhost:8080/hb/`。

为了防止出意外，你应该用**Tomcat9.0**，以及去Mysql数据库中建库，Sql脚本在[这里](https://github.com/inkss/hotelbook-JavaWeb/blob/master/src/sql/sql.sql)。
